POST http://localhost:3001/api/patients/d2773336-f723-11e9-8f0b-362b9e155667/entries
Content-Type: application/json

{
	"description": "Selkeästi juovuksissa",
	"date": "2020-10-12",
	"specialist": "Dr. Heikki Malkavaara",
	"diagnosisCodes": [ "H35.29" ],
	"type": "HealthCheck",
	"healthCheckRating": 3
}